### ISSUE TITLE
utuility function are missing in docs ?

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#106]
@buzmakov: how to add modules wpg_uti_*.py in [WPG docs](http://wpg.readthedocs.io/en/latest/index.html)?

**Comment by buzmakov** [comment]
One should create file for each wpg_uti_*.py like https://raw.githubusercontent.com/samoylv/WPG/develop/docs/optical_elements.rst and add reference in https://raw.githubusercontent.com/samoylv/WPG/develop/docs/index.rst

**Comment by samoylv** [comment]
1) I see, it is not generated automatically. BTW in optical elements rst-file  some available optical elements are not listed. Does it mean that they should be updated?
2) only one recvord should be in every file (see below), then all the functions in the file will be included? 
:mod:`wpg.wpg_uti_wf` module
----------------------------------

.. automodule::wpg.wpg_uti_wf
    :members:
    :undoc-members:
    :show-inheritance:

**Comment by buzmakov** [comment]
1) I add aliases to SRW optical elements manually ( I don't remember why, but it work)
2) I think yes. I don't remember exactly.

**Comment by samoylv** [comment]
implemented in [5921a0852aecff278e3d1a6eff62cab16901cf92](https://github.com/samoylv/WPG/commit/5921a0852aecff278e3d1a6eff62cab16901cf92)
