### ISSUE TITLE
Add arrtibutes import

### ISSUE THREAD

**Issue by buzmakov** [samoylv/WPG#11]
Attributes of HDF5 fields should be stored after propagation

**Comment by buzmakov** [comment]
no

**Comment by buzmakov** [comment]
To clarify/discuss importing - exporting process.

1) When we load wavefront we should load 
wavefront mandatory fields with

**Comment by samoylv** [comment]
?

**Comment by samoylv** [comment]
what else should be done?

**Comment by samoylv** [comment]
check how it works after adding the attributes to xpd FEL source files (https://github.com/samoylv/xpd/issues/5)

**Comment by samoylv** [comment]
done
