### ISSUE TITLE
Request: Add setup.py

### ISSUE THREAD

**Issue by CFGrote** [samoylv/WPG#129]
Hi,
I suggest to add a minimal `setup.py` file to the WPG root dir, such as:

```
from setuptools import setup

setup(
    name='WPG',
    packages=['wpg',
             ],
    license='EuXFEL',
)
```

One could then do
```
pip install -e .
```
from the WPG root dir and you could get rid of all the `sys.path.insert(...)` statements.

**Comment by buzmakov** [comment]
@CFGrote Thanks for the tip.
