### ISSUE TITLE
Add history support for S2E 

### ISSUE THREAD

**Issue by buzmakov** [samoylv/WPG#15]
* We should add option wf.add_hsitory(hdf5_file) or/and wf.add_history(other_wf)
Moreover now wavefront object contain all fields from parent HDF5 file. For example, if input file contains /misc/... output file will contain same /misc/... and /history/parent/misc/...
* If we add /history/parent/data as links to Datasets in other files showld we keep absolute file names like /data/S2E/data/prop_in.h5 or relative part ../../data/prop_in.h5?
*If anyone change original prop_in.h5, how we will track it? should we check and store some hashes?

We should discuss and decide what we should do with this. 
May be we should invite Chuck and Adrian to this discussion?

**Comment by samoylv** [comment]
4AK: check how it works with regular wavefronts, see the s2e prop script
