### ISSUE TITLE
Implement get_pulse_energy() and get_intensity()

### ISSUE THREAD

**Issue by buzmakov** [samoylv/WPG#16]
1.
get_pulse_energy(): return value in [J] is a total sum of intensity multiplied by (dx*dy*dSlice)*K, 
where K=1e-6, because |E|^2=W/mm^2 for 't' and J/eV/mm^2 for 'f' representation
open issue: 
what is the dSlice for 'f'? should be $\delta E_{ph}/E_{ph}$
2. 
get_intensity() should return the value, multiplied by pixel size dx*dy measured in mm^2 (?)

**Comment by samoylv** [comment]
should be placed into uti_wpg_wf()

**Comment by samoylv** [comment]
from issue #41 which has been closed

input parameters:

wf - wavefront structure

bit_mask(wf.params.Mesh.nx,wf.params.Mesh.ny) - to define an aperture, optional

the function returns integral intensity, units - number of photons or J (i.e. Nph*h\nu) - some constants, e.g. charge of electron should be defined

For t-dependent pulses everything except applying the bitmask is already implemented and checked in FELsource diagnostics.

The units for stationary-state, i.e E(x,y), - TBD

**Comment by samoylv** [comment]
get_intensity() is the name of Wavefront method
bit-mask can be implemented as an aperture in most cases
