### ISSUE TITLE
add moments to standard libraries

### ISSUE THREAD

**Issue by guerass** [samoylv/WPG#42]

**Comment by samoylv** [comment]
could you please provide a link to /copy of piece of code

**Comment by samoylv** [comment]
* look through 
http://www.exponenta.ru/educat/class/courses/tv/theme0/3.asp
https://ned.ipac.caltech.edu/level5/Leo/Stats1_3.html
* calculate 
  - the mean value (the first moment about 0) 
  - the mean-square deviation or dispersion/variance (the second central moment)
  - (?) asymmetry coefficient, i.e. the_third_central_moment/variance^(3/2)

**Comment by guerass** [comment]
normalization is needed (in statistics, there is always probability density p(x), where integral(p(x)dx)=1)

**Comment by samoylv** [comment]
for 3d moment see https://en.wikipedia.org/wiki/Skewness
