### ISSUE TITLE
Parameter --pylab=inline in Step 6 of Windows installation guide seems not to work

### ISSUE THREAD

**Issue by meyerann** [samoylv/WPG#45]

**Comment by samoylv** [comment]
what diagnostics is generated?

**Comment by meyerann** [comment]
The support has been removed and %pylab inline or %matplotlib inline should be used.

**Comment by samoylv** [comment]
in which version of ipython notebook this support removed? - It may have impact on installation for other OS as well...

**Comment by meyerann** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/11921805/7115611/86f8ecae-e1ea-11e4-88e3-d38b6f8d26c1.PNG)

**Comment by buzmakov** [comment]
We should remove '--pylab inline' from command line parameters and add
'%pylab inline' in all tutorials.
13 Апр 2015 г. 15:37 пользователь "meyerann" <notifications@github.com>
написал:
