### ISSUE TITLE
old version notebook on server

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#46]
how to make notebooks compatible? does it make sense to ask Janush about ipython server installation?

**Comment by buzmakov** [comment]
I use IPython v3.1, it have updated version of notebook format.  IPython
2.4 support this format.
Our karaboo installation have IPython 1.

I'll convert notebooks in half hour.
16 Апр 2015 г. 12:16 пользователь "samoylv" <notifications@github.com>
написал:

**Comment by samoylv** [comment]
>I'll convert notebooks in half hour. 
hmm, in what direction? if one is working within new IPython, the notebooks are automatically converted into new format. QUESTION: How to keep updated examples (after processing and auto-using updated version of the format) in repo?

**Comment by buzmakov** [comment]
All notebooks in repository will in ipython v1 format to keep comparability
with karaboo.

I use v4 format only for my pwn scripts.

**Comment by buzmakov** [comment]
I convert files.
Please use *.v3.ipynb files.

**Comment by samoylv** [comment]
I cannot find .v3.ipynb files in github,
