### ISSUE TITLE
 9fs_20_T not able to run on 2 cores, reallocate memory error

### ISSUE THREAD

**Issue by meyerann** [samoylv/WPG#47]
The execution needs about 40minutes and then the error you can see in the picture occur. It also occurs by execution with  9fs_35_T on 2 cores. On 1 core it is running successful and needs about 25 minutes.

**Comment by samoylv** [comment]
2 meyerann: I removed the screen shot - it is better to use e-mail for such info

**Comment by samoylv** [comment]
moved to s2e prop issues
