### ISSUE TITLE
strange order of get_limit() output

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#53]
here:
https://github.com/samoylv/WPG/blob/develop/wpg/wavefront.py#L329 
2AB: do you remember why is there such a strange sequence, e.g by default, for 
`axis == 'z': return sr.xMin, sr.xMax, sr.yMax, sr.yMin`

Is it determined by usage in  `imshow(wfr_data, extends=wrf.get_limits()))` ?

**Comment by buzmakov** [comment]
Yes,
get_limits used only for simplify imshow() usage.
If it's work don't touch it.
Do you find strange behavior of your code with this function?

**Comment by samoylv** [comment]
no, actually we should change the Tutorial examples plot_2d() for the mirror surface distortions as a phase screen: there the limits are definitely wrong and now I seems to understand why
