### ISSUE TITLE
import error in nanolenses notebook 

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#56]
```
from wpg.converters.nanolenses import EdfFile

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-c9683c85fe38> in <module>()
      1 import wpg
----> 2 from wpg.converters.nanolenses import EdfFile

ImportError: No module named nanolenses

```

**Comment by buzmakov** [comment]
All works for me in master and develop

**Comment by samoylv** [comment]
and in the third branch?

**Comment by samoylv** [comment]
no, it should not depend on the branch, what version of ipython do you use?

**Comment by buzmakov** [comment]
[makov-G46VW]➜  WPG git:(feature/optical_elements) ✗ ipython
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Oct 19 2015, 18:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from wpg.converters.nanolenses import EdfFile

In [2]:

**Comment by samoylv** [comment]
thanks. it means IPython 4.0.0 --

and I tried with 
```
import IPython
IPython.__version__
'3.2.1'
```
maybe the syntax is not supported for earlier versions??

**Comment by buzmakov** [comment]
No, Python 2.7 used in all cases.

**Comment by samoylv** [comment]
and IPython version does not matter you meant?

**Comment by buzmakov** [comment]
Yes, version of IPython doesn't matter.
Could you please check this in master or develop branch?

**Comment by samoylv** [comment]
yes, with develop branch I have the same error
git branch
* develop
  feature/optical_elements
  master

**Comment by buzmakov** [comment]
Is it on server or your laptop?
Have you file wpg/converters/nanolenses/EdfFile.py?

**Comment by samoylv** [comment]
on laptop
yes I have

**Comment by buzmakov** [comment]
Please try create empty __init__.py file in wpg/converters/nanolenses/

**Comment by samoylv** [comment]
aga, it helped!
