### ISSUE TITLE
which cmap use for intensity imshow()?

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#60]
comment from CFGrote:
although widely used, gnuplot is not a good choice (though better than
jet) because not perceptually uniform. same goes for hot. if you want a
"rainbow" like colormap, use inferno, plasma, or magma. personally, i
like viridis or bones best. for phase plots, a diverging map might be
suitable, e.g. RdBu or coolwarm. see also
http://matplotlib.org/users/colormaps.html

**Comment by samoylv** [comment]
inferno is used in wpg_uti_wf.py, (locally)

**Comment by buzmakov** [comment]
Good presentation about new default colormap in matplotlib 2.0
https://www.youtube.com/watch?v=xAoljeRJ3lU

**Comment by samoylv** [comment]
one should find a suitable cmap at server, for older matplotlib  installation...

**Comment by buzmakov** [comment]
RdBu colormap exist on exflst314 for python 2 and python 3 installation

**Comment by CFGrote** [comment]
ok. that's a good choice for phase maps. in the absence of viridis in
py2, i suggest YlGbBu_r (min = dark blue, max = bright yellow,
perceptually monotonic in between) for amplitudes.

carsten


On 05/03/2016 11:10 AM, Alexey Buzmakov wrote:
> RdBu colormap exist on exflst314 for python 2 and python 3 installation
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/samoylv/WPG/issues/60#issuecomment-216474448>
> 

-- 
--
Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603
