### ISSUE TITLE
Small changes in plotting utilities

### ISSUE THREAD

**Issue by CFGrote** [samoylv/WPG#61]
Hi, I made some modifications to my copy of wpg_uti_wf to make the plots a bit nicer (include x and y projection next to the profile. Just a suggestion.

----
def plot_t_wf(wf, save='', range_x=None, range_y=None):
    """
    plot wavefront in time domain (obligatory?) and R-space

    :params: wf: wavefront structure
    :params: save: Whether to save the figure on disk
    :type:  string for filename. Empty string '' means don't save.
    """
    wf_intensity = wf.get_intensity().sum(axis=-1)

    plt.figure(figsize=(10,10), dpi=100)
    profile = plt.subplot2grid((3,3), (1,0), colspan=2, rowspan=2)
    xmin,xmax,ymax,ymin = wf.get_limits()
    profile.imshow(wf_intensity, extent=[xmin*1.e3,xmax*1.e3,ymax*1.e3,ymin*1.e3])
    profile.set_aspect('equal', 'datalim')

    x = numpy.linspace(xmin*1.e3,xmax*1.e3,wf_intensity.shape[0])
    y = numpy.linspace(ymin*1.e3,ymax*1.e3,wf_intensity.shape[1])
    profile.set_xlabel('$mm$',fontsize=12)
    profile.set_ylabel('$mm$',fontsize=12);

    x_projection = plt.subplot2grid((3,3), (0,0), sharex=profile, colspan=2)
    x_projection.plot(x, wf_intensity.sum(axis=0), label='x projection')
    if range_x is None:
        profile.set_xlim([xmin*1.e3, xmax*1.e3])
    else:
        profile.set_xlim([-range_x/2., range_x/2.])

    y_projection = plt.subplot2grid((3,3), (1,2), rowspan=2, sharey=profile)
    y_projection.plot(wf_intensity.sum(axis=1), y, label='y projection')

    # Hide minor tick labels.
    plt.minorticks_off()

    if range_y is None:
        profile.set_ylim([ymin*1.e3, ymax*1.e3])
    else:
        profile.set_ylim([-range_y/2., range_y/2.])

    if save != '':
        # Add parameters.
        plt.savefig(save)
    else:
        plt.show()

def plot_t_wf_a(wf, save='', range_x=None, range_y=None):
    """
    plot wavefront in Q-space

    :params: wf: wavefront structure
    """
    wf_intensity = wf.get_intensity().sum(axis=-1)
    plt.figure(figsize=(10,10), dpi=100)
    profile = plt.subplot2grid((3,3), (1,0), colspan=2, rowspan=2)
    xmin,xmax,ymax,ymin = wf.get_limits()

    profile.imshow(wf_intensity, extent=[xmin*1.e6,xmax*1.e6,ymax*1.e6,ymin*1.e6])
    profile.set_aspect('equal', 'datalim')

    x = numpy.linspace(xmin*1.e6,xmax*1.e6,wf_intensity.shape[0])
    y = numpy.linspace(ymin*1.e6,ymax*1.e6,wf_intensity.shape[1])
    profile.set_xlabel(r'$\mu$rad',fontsize=12)
    profile.set_ylabel(r'$\mu$rad',fontsize=12);

    x_projection = plt.subplot2grid((3,3), (0,0), sharex=profile, colspan=2)
    x_projection.plot(x, wf_intensity.sum(axis=0), label='x projection')
    if range_x is None:
        profile.set_xlim([xmin*1.e6, xmax*1.e6])
    else:
        profile.set_xlim([-range_x/2., range_x/2.])

    y_projection = plt.subplot2grid((3,3), (1,2), rowspan=2, sharey=profile)
    y_projection.plot(wf_intensity.sum(axis=1), y, label='y projection')

    # Hide minor tick labels.
    plt.minorticks_off()

    if range_y is None:
        profile.set_ylim([ymin*1.e6, ymax*1.e6])
    else:
        profile.set_ylim([-range_y/2., range_y/2.])

    if save != '':
        plt.savefig(save)
    else:
        plt.show()

def look_at_q_space(wf, output_file = None, savefig='', range_x=None, range_y=None):
    """
    change wavefront representation from R- to Q-space and store it in output file.

    :param wf: Wavefront object in R-space representation
    :param output_file: if parameter present - store propagaed wavefront to file
    :return: propagated wavefront object:
    """
    if True: #isinstance(wf, Wavefront):
        #print wf
        wfr = Wavefront(srwl_wavefront=wf._srwl_wf)
    else:
        print( 'no wavefront specified...')
        return

    if not wf.params.wSpace=='R-space':
        print( 'space should be in R-space, but not '+ wf.params.wSpace)
        return
    srwl_wf = wfr._srwl_wf
    srwl_wf_a = copy.deepcopy(srwl_wf)
    srwl.SetRepresElecField(srwl_wf_a, 'a')
    wf_a = Wavefront(srwl_wf_a)
    if not output_file is None:
        print('store wavefront to HDF5 file: '+ output_file+'...')
        wf_a.store_hdf5(output_file); print('done')

    print(  calculate_fwhm(wf_a))
    plot_t_wf_a(wf_a, save=savefig, range_x=range_x, range_y=range_y)
    return

**Comment by samoylv** [comment]
could  you commit the code? I added you as collaborator, as discussed.
but not forget please to add the parameters descriptions in function headers))

**Comment by samoylv** [comment]
\+ fixed  a bug with  x/y projections fixed   [here](https://github.com/samoylv/WPG/commit/131f4a5ed7f442f834c0c8156bae1f39efac4fc2#diff-a79c65cc56f661ae1aa8af5d8862f246L135)
