### ISSUE TITLE
Add PlaneMirror to optical_elements

### ISSUE THREAD

**Issue by CFGrote** [samoylv/WPG#62]
A plane mirror with a non-zero mirror profile is currently done in two steps:
* Setup a phase screen propagator using WF_dist
* "Fill" the phase screen propagator using calculateOPD.

I suggest adding a new PlaneMirror(**kwargs) function that takes the dimensions (mirror length, angle wrt optical axis, mirror profile data (or file) and returns the phase screen propagator.

**Comment by samoylv** [comment]
Agreed, will add in the next update.

**Comment by samoylv** [comment]
Mirror_plane() added
