### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by CFGrote** [samoylv/WPG#65]
I tried pythoh SRWLIB_Example??.py, but get 
Traceback (most recent call last):
  File "SRWLIB_Example01.py", line 8, in <module>
    from srwlib import *
  File "/home/grotec/Work/XFEL/Codes/WPG/wpg/srwlib.py", line 6, in <module>
    from . import srwlpy as srwl
ValueError: Attempted relative import in non-package

Are they meant to work or just for reference?

I really recommend unittesting and only accept patches that pass all tests (See e.g. [https://github.com/eucall-software/simex_platform/tree/master/python/unittest](url) .

**Comment by buzmakov** [comment]
This files are original SRW examples. We are not use it, but keep as an examples.

We use tutorials https://github.com/samoylv/WPG/tree/develop/samples/Tutorials for checking consistence of WPG.

**Comment by samoylv** [comment]
well, 
* SRWLIB_ExampleXX.py are SRW examples from Oleg, they are copied 'as-is'. 
@buzmakov : could you comment on errror? is this somehow connected with migration to py 3?
* the idea about regressive testsuite for patches sounds good, but your link goes to Error 404 page...
* we can discuss the issue if such examples are meant to work this week with the team involved in SRW development...

**Comment by CFGrote** [comment]
ok, i understand.
 correct link is

https://github.com/eucall-software/simex_platform/tree/master/python/unittest

**Comment by buzmakov** [comment]
I remove SRW examples from wpg directory to do not confuse users, They are still available in build/tmp/SRW/env/work/srw_python

**Comment by samoylv** [comment]
ok
