### ISSUE TITLE
py3 clashes

### ISSUE THREAD

**Issue by CFGrote** [samoylv/WPG#66]
I still get traces of the following sort when using prop module in s2e:

File "/home/grotec/Work/XFEL/Codes/SIMEX/simex_new_cmake/sw/lib/python/prop/propagateSE.py", line 165, in propagate
    wf.load_hdf5(in_fname)
  File "/home/grotec/Work/XFEL/Codes/SIMEX/simex_new_cmake/sw/lib/python/wpg/wavefront.py", line 188, in load_hdf5
    self._update_from_dict(utils.load_dict_slash_hdf5(file_name))
  File "/home/grotec/Work/XFEL/Codes/SIMEX/simex_new_cmake/sw/lib/python/wpg/wavefront.py", line 148, in _update_from_dict
    self._wf_fields[key].value = value
  File "/home/grotec/Work/XFEL/Codes/SIMEX/simex_new_cmake/sw/lib/python/wpg/glossary.py", line 1221, in value
    self._wf._srwl_wf.arEy = array.array('f')
TypeError: must be char, not unicode

which can be solved by replacing 'f' with str(u'f') in glossary.py (lines 1165 and 1220).

greping for 'f' i find at least ~50 other places that might pose an issue, should probably all be replaced by str(u'f').

**Comment by samoylv** [comment]
@buzmakov - your comments?

**Comment by buzmakov** [comment]
Please check it ant close if all fixed

**Comment by samoylv** [comment]
yes, certainly. sorry for too late comment

**Comment by samoylv** [comment]
@CFGrote: could you please check? installed at the server, under .../beta/WPG/

**Comment by CFGrote** [comment]
ok will check

**Comment by CFGrote** [comment]
looks ok in the server beta installation. have to make sure that this fix goes into simS2E and simex as well. guess when you push to develop those will automatically  catch up. 

closed.

**Comment by samoylv** [comment]
OK, thanks!
@buzmakov :
please update the /latest/ installation on server before checking simex environments,unless I let you explicitly know that I did it (I am still working on Xtal propagator)

**Comment by buzmakov** [comment]
I update the /latest/ installation on server

**Comment by samoylv** [comment]
@buzmakov thanks a lot! It would be great if you could compile the readthedocs, I've just updated the guidelines for running on xfel server.

**Comment by buzmakov** [comment]
done
