### ISSUE TITLE
wf.load_hdf5() does not work with python3?

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#67]
```
wf = Wavefront()`
wf.load_hdf5(filename) 
```

`filename` - h5 file generated by [xpd](https://in.xfel.eu/xpd/)

keys_string = keys_string.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by buzmakov** [comment]
Fixed version updated on server

**Comment by samoylv** [comment]
well, now there is a problem with load_hdf5 in python 2.7:
in wavefront.py l.71, https://github.com/samoylv/WPG/blob/develop/wpg/wavefront.py#L71
Type Error "must be char, not unicode"

**Comment by samoylv** [comment]
fixed, updated in latest/
