### ISSUE TITLE
WPG Anaconda 3.5 error (importing) while running in Windows Tutorial sample

### ISSUE THREAD

**Issue by Angelrf86** [samoylv/WPG#79]
Hello,
While using Anaconda 3.5 to run the Tutorials samples at WPG. I have had problems while importing the lib necessary for the different examples Tutorials. It seems the problem comes for a wrong path description, as says file not find.

An example of the previous said:
The command line is the following
import srwlpy as srwl ---> No find file to import
-------------
The problem seems to be solved by writting "wpg." before the file to import
import wpg.srwlpy as srwl --> Finds file to import

This problem seems to be in all the different samples in wpg while running with Anaconda 3.5 after importing the files from srw.

Thanks,
Angel

**Comment by samoylv** [comment]
the problem (as soon as I remember) is the following:
one has to add  `wpg.`  in most of import directives of the srw python files used
@Angelrf86 am I right?

**Comment by Angelrf86** [comment]
Yes, that was the problem we were having last Friday

**Comment by buzmakov** [comment]
It is issue in isntallation instructions for Windows,
Now you not need copy *.py file form SRW sources. (srwlib.py rewrite good version)

**Comment by Angelrf86** [comment]
Hi @buzmakov,

Starting from a new unzip folder. Should I copy all the examples and files (*.py)  from the SRW source to wpg?
Is the second step, to copy the file SRWLIB.py file from the folder lib in SRW what I should Skip?

If both are affirmative, I have a error while running the file SRWLIB_example14.py, the error says error importing "DLL load failed:The specified module could not be found" referring to line 9 "from srwlib impor * "

**Comment by buzmakov** [comment]
Hi @Angelrf86 ,
I try to fix installation issues on Windows, but now I'm on vacations and have low connectivity, so I can't check all configurations.
I check it with Anaconda python 3.5.1 x64.
All fixes now  in separate wpg branch https://github.com/samoylv/WPG/tree/feature/windows_issues .
You can download zip file from here: https://github.com/samoylv/WPG/archive/feature/windows_issues.zip

1) Unzip it
2) Download this precompiled SRW module https://github.com/ochubar/SRW/blob/master/env/work/srw_python/lib/srwlpy3_5_x64.pyd and save it as WPG/wpg/srwlpy.pyd
3) check wpg import `cd WPG; ipython -c 'import wpg'`

If all will work fine I'll update documentation and merge changes to develop branch.

Thank you for your help in testing.

@samoylv Liuba, I check tutorials on Linux - all work fine. but do not check it on Windows.

**Comment by samoylv** [comment]
@buzmakov Alexey, thank you! Unfortunately I have no chance to ask anybody else to test it on Windows at XFEL: everything is packed for move this weekend to Schenefeld...

**Comment by Angelrf86** [comment]
Dear @buzmakov,
Thanks for your help, the Tutorials are running properly. Also the %matplotlib inline command.
While runing the Exmaple 14 from SRW we are having the follwoing message: 
Plotting the results (blocks script execution; close all graph windows to proceed) ... done​
For this I have had to change the import file from:
import swrlib
to
import wpg.swrlib.
Hope not to have disturb you a lot during this days.
Enjoy your weekends and we talk when you are back.

Cheers,
Angel
