### ISSUE TITLE
feature/srw_update - misprint in SRW distributive?

### ISSUE THREAD

**Issue by samoylv** [samoylv/WPG#89]
https://github.com/buzmakov/SRW/commit/b89f165bfdd4cff6968b84f1b98247161d413622

**Comment by samoylv** [comment]
did not help, with this makefile
https://github.com/buzmakov/SRW/blob/feature/srw_lite_update/Makefile
one gets the following error (with or without correction mentioned above):

```
cd /Users/lsamoylv/code/ghub/srw_update/build/tmp/SRW; make all;
Makefile:1: *** missing separator.  Stop.
make[1]: *** [srw] Error 2
make: *** [core] Error 2
```

**Comment by buzmakov** [comment]
It is seems that is a bug in SRW Makefile.
I'll try fix it

пн, 10 окт. 2016 г. в 20:12, samoylv <notifications@github.com>:

**Comment by mrakitin** [comment]
Please try to use my file https://github.com/mrakitin/SRW/blob/master/Makefile. That should fix the issue with `make all`. More details in https://github.com/mrakitin/SRW/issues/13.

**Comment by mrakitin** [comment]
Lyuba, Alexey, do you have `python-dev` package installed? It's required since it provides `Python.h` header file. See https://github.com/mrakitin/SRW/issues/14 for more details.

**Comment by buzmakov** [comment]
Yes,  sure we have.
The problem is no in building srwlpy.cpython-35m-x86_64-linux-gnu.so file.
The problem is that that Makefile try copy srwlpy.so not
srwlpy.cpython-35m-x86_64-linux-gnu.so.

We can discuss it shortly using Skype,  if you have possibility.

вт, 11 Окт 2016 г., 19:09 Maksim Rakitin <notifications@github.com>:

Lyuba, Alexey, do you have python-dev package installed? It's required
since it provides Python.h header file. See mrakitin/SRW#14
<https://github.com/mrakitin/SRW/issues/14> for more details.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/samoylv/WPG/issues/89#issuecomment-252964174>, or mute
the thread

**Comment by mrakitin** [comment]
Why do you need `srwlpy.cpython-35m-x86_64-linux-gnu.so`? As far as I know, only `cpp/gcc/srwlpy.so` is created during compilation. That compiled file is being copied by `make`. Is it different in your case?

**Comment by mrakitin** [comment]
Alexey, I was able to reproduce the issue with `srwlpy.cpython-35m-x86_64-linux-gnu.so` on my Anaconda3 environment:
```bash
g++ -pthread -shared -L/home/vagrant/anaconda3/lib -Wl,-rpath=/home/vagrant/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.5/home/vagrant/src/mrakitin/SRW/cpp/src/clients/python/srwlpy.o -L/home/vagrant/src/mrakitin/SRW/cpp/gcc -L/home/vagrant/src/mrakitin/SRW/ext_lib -L/home/vagrant/anaconda3/lib -lsrw -lm -lfftw -lpython3.5m -o ../gcc/srwlpy.cpython-35m-x86_64-linux-gnu.so
cp ../gcc/srwlpy.so ../../env/work/srw_python/
cp: cannot stat ‘../gcc/srwlpy.so’: No such file or directory
make[1]: *** [srwlpy.so] Error 1
make[1]: Leaving directory `/home/vagrant/src/mrakitin/SRW/cpp/py'
make: *** [pylib] Error 2
(py3k) ✘-2 ~/src/mrakitin/SRW [master|…4]
19:10 $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        cpp/gcc/libsrw.a
        cpp/gcc/srwlpy.cpython-35m-x86_64-linux-gnu.so
        cpp/py/build/
        ext_lib/libfftw.a

nothing added to commit but untracked files present (use "git add" to track)
```
It looks like Anaconda's python is tweaked to produce this long name, not just `srwlpy.so`. Your fix in https://github.com/buzmakov/SRW/commit/702eac5ba94a4ced343ffdb7d295fcf582144147 looks reasonable, I'll implement it in my branch of SRW. Thanks for the hint!

**Comment by mrakitin** [comment]
Please see my fix in https://github.com/mrakitin/SRW/commit/2421b18923a4bb7314067455863f412f028d73c3. Please note, that the `clean` directive in the main `Makefile` should be updated as well to have a comprehensive solution.

**Comment by samoylv** [comment]
BTW, I observed the same behaviour with 
OS X, Yosemite 10.10.5 
python and other packages were installed using macport (no Anaconda)
with the fixed makefile it runs smoothly

**Comment by mrakitin** [comment]
Glad to hear :)

**Comment by samoylv** [comment]
Actually, with the fix made by Alexey))
I just mentioned that  it is not Anaconda thing, but more general.  
I am not sure if it is a feature for Py 3  environment only.
Thanks a lot for fast feedback

**Comment by Angelrf86** [comment]
Thank you!
Angel

**Comment by mrakitin** [comment]
Yes, Alexey suggested a great and simple fix, we implemented it in our SRW versions. Thanks Alexey!

**Comment by samoylv** [comment]
resolved
